### ISSUE TITLE
mirdeep2_patch

### ISSUE THREAD

**Issue by minal14kadam** [Drmirdeep/mirdeep2_patch#1]
I tried linking mirdeep2_patch to mirdeep2. but i found this error.

mv: missing destination file operand after '.orig'
Try 'mv --help' for more information.
ln: failed to create symbolic link 'Folder/mirdeep2_patch-master/miRDeep2_patch.pl': No such file or directory
File has been moved to .orig and the current /home/minal/Downloads/Untitled Folder/mirdeep2_patch-master/miRDeep2_patch.pl has been linked to

Please help me in solving the issue

**Comment by Drmirdeep** [comment]
looks like you have not miRDeep2 in your PATH variable.
what happens when you type 

which miRDeep2.pl

on the command line?

If it says file not found  or does not list a path to the file then please use the install.pl script first before patching.
